[[fastloess]]
arch = "aarch64"
git-tree-sha1 = "e61177ee9f14679009218131b5390af1c8dbef7d"
os = "macos"

    [[fastloess.download]]
    sha256 = "e0ecd060e3b1f280e2959a30d1230b031a73b430b13571b49e5560e94820d678"
    url = "https://github.com/JuliaBinaryWrappers/fastloess_jll.jl/releases/download/fastloess-v2.0.0+0/fastloess.v2.0.0.aarch64-apple-darwin.tar.gz"
[[fastloess]]
arch = "aarch64"
git-tree-sha1 = "f1dfe4c60b2a65fbc26de51cfa0615e12f392dbe"
libc = "glibc"
os = "linux"

    [[fastloess.download]]
    sha256 = "accfe7e82fc45262d5d5ac5ce72931928a97937bd32de9c65050e8a7c6612e17"
    url = "https://github.com/JuliaBinaryWrappers/fastloess_jll.jl/releases/download/fastloess-v2.0.0+0/fastloess.v2.0.0.aarch64-linux-gnu.tar.gz"
[[fastloess]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "85fc11d902851304f3f5710acf22ea6e7bb74af2"
libc = "glibc"
os = "linux"

    [[fastloess.download]]
    sha256 = "8ac9ea628bbc87b19ba98aebfedbda9fe5f0d3143a4f0deb6ad8f874a6d46521"
    url = "https://github.com/JuliaBinaryWrappers/fastloess_jll.jl/releases/download/fastloess-v2.0.0+0/fastloess.v2.0.0.armv6l-linux-gnueabihf.tar.gz"
[[fastloess]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dab376798580529ba10e3c9b2fa3638ef4d5a0fa"
libc = "glibc"
os = "linux"

    [[fastloess.download]]
    sha256 = "2487d8beae9cb807685aa73806227828fbc3f5aa94b0338a92a982c62c6e94d9"
    url = "https://github.com/JuliaBinaryWrappers/fastloess_jll.jl/releases/download/fastloess-v2.0.0+0/fastloess.v2.0.0.armv7l-linux-gnueabihf.tar.gz"
[[fastloess]]
arch = "i686"
git-tree-sha1 = "35f3f750ed5e2153afc1fc32ed62fbffb0d06bac"
libc = "glibc"
os = "linux"

    [[fastloess.download]]
    sha256 = "ee6ef85bc325107e45713abb8dcfbe86bee1fadb69947ce86fd0ed707760fba1"
    url = "https://github.com/JuliaBinaryWrappers/fastloess_jll.jl/releases/download/fastloess-v2.0.0+0/fastloess.v2.0.0.i686-linux-gnu.tar.gz"
[[fastloess]]
arch = "powerpc64le"
git-tree-sha1 = "939099b4836762947bdd0d50f3f079ed7e1c71d4"
libc = "glibc"
os = "linux"

    [[fastloess.download]]
    sha256 = "9406a0f34f19cc3309e12e1af898430a12b15d2739ddd7f6b476a0a659e4f27c"
    url = "https://github.com/JuliaBinaryWrappers/fastloess_jll.jl/releases/download/fastloess-v2.0.0+0/fastloess.v2.0.0.powerpc64le-linux-gnu.tar.gz"
[[fastloess]]
arch = "x86_64"
git-tree-sha1 = "a10ee8a28e137404ae9a93bbb31d9e17bc0e16dd"
os = "macos"

    [[fastloess.download]]
    sha256 = "fc97bc11349af20a64094f15cef6e59c6cc378f479f2e823b3a081cf62566dd9"
    url = "https://github.com/JuliaBinaryWrappers/fastloess_jll.jl/releases/download/fastloess-v2.0.0+0/fastloess.v2.0.0.x86_64-apple-darwin.tar.gz"
[[fastloess]]
arch = "x86_64"
git-tree-sha1 = "e96b561146b075ad11235c2440df357e1d8957f4"
libc = "glibc"
os = "linux"

    [[fastloess.download]]
    sha256 = "b8cdeaf5f8e63ef283a0d9e51f10f438451971f50ae833c719884216b967d6cf"
    url = "https://github.com/JuliaBinaryWrappers/fastloess_jll.jl/releases/download/fastloess-v2.0.0+0/fastloess.v2.0.0.x86_64-linux-gnu.tar.gz"
[[fastloess]]
arch = "x86_64"
git-tree-sha1 = "8f08ba22705bcfcf138f9ddc782ab59ba3e32b33"
os = "windows"

    [[fastloess.download]]
    sha256 = "967df294c7718edf9b1cdafee5c3787f1fa2ce60080728e0d26945763aded191"
    url = "https://github.com/JuliaBinaryWrappers/fastloess_jll.jl/releases/download/fastloess-v2.0.0+0/fastloess.v2.0.0.x86_64-w64-mingw32.tar.gz"
