[[fastloess]]
arch = "aarch64"
git-tree-sha1 = "0da88118b26f8d986192f24c9556395b2e544bb3"
os = "macos"

    [[fastloess.download]]
    sha256 = "3777b5bf8e826e23293f658b7273d43262549e416d40eb4cd1edde8a3b7aa226"
    url = "https://github.com/JuliaBinaryWrappers/fastloess_jll.jl/releases/download/fastloess-v1.0.0+0/fastloess.v1.0.0.aarch64-apple-darwin.tar.gz"
[[fastloess]]
arch = "aarch64"
git-tree-sha1 = "87b9b177d58ede39cc4b9bd585f2a62292babc3a"
libc = "glibc"
os = "linux"

    [[fastloess.download]]
    sha256 = "72758705adcd1c5b2f63c2edaec366916b36a0ed4717ce9b0b9a413785d20666"
    url = "https://github.com/JuliaBinaryWrappers/fastloess_jll.jl/releases/download/fastloess-v1.0.0+0/fastloess.v1.0.0.aarch64-linux-gnu.tar.gz"
[[fastloess]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fcb4f5dfdf470177808f522c2bca335d70a96384"
libc = "glibc"
os = "linux"

    [[fastloess.download]]
    sha256 = "5cea97ebfe79030ee523067ebc7cd19192aacb795d6e4dbc5cc032ef59ccb8d1"
    url = "https://github.com/JuliaBinaryWrappers/fastloess_jll.jl/releases/download/fastloess-v1.0.0+0/fastloess.v1.0.0.armv6l-linux-gnueabihf.tar.gz"
[[fastloess]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "14085ca0a91be36a0818bb0fde08254cf5704bb5"
libc = "glibc"
os = "linux"

    [[fastloess.download]]
    sha256 = "cdaba160a63ad4c151ae6782734751acce72c2f9864d060bd3fa17717edfab9f"
    url = "https://github.com/JuliaBinaryWrappers/fastloess_jll.jl/releases/download/fastloess-v1.0.0+0/fastloess.v1.0.0.armv7l-linux-gnueabihf.tar.gz"
[[fastloess]]
arch = "i686"
git-tree-sha1 = "61b245eb437afe2c9ec40a939c19d52570e7e84f"
libc = "glibc"
os = "linux"

    [[fastloess.download]]
    sha256 = "e777d1346bf0d9db2d6ee2e79ca5b38ea9c63540da7c42d0a53c7ae92f87cab8"
    url = "https://github.com/JuliaBinaryWrappers/fastloess_jll.jl/releases/download/fastloess-v1.0.0+0/fastloess.v1.0.0.i686-linux-gnu.tar.gz"
[[fastloess]]
arch = "powerpc64le"
git-tree-sha1 = "3b533a1c01f355efcb7ea8c6d4cc1a02d5c6fbdd"
libc = "glibc"
os = "linux"

    [[fastloess.download]]
    sha256 = "3e5c87c438e3097070367c9c1b28c7c1b786ac14af4aba5eee6c1208f2776e7e"
    url = "https://github.com/JuliaBinaryWrappers/fastloess_jll.jl/releases/download/fastloess-v1.0.0+0/fastloess.v1.0.0.powerpc64le-linux-gnu.tar.gz"
[[fastloess]]
arch = "x86_64"
git-tree-sha1 = "ec3e2ffd35749e061a08067bc89bfd1c84fc9408"
os = "macos"

    [[fastloess.download]]
    sha256 = "531f690b6f3d51cc3f954fc289fc72aa54fa204f158ce6fa06fbe9df936f12f9"
    url = "https://github.com/JuliaBinaryWrappers/fastloess_jll.jl/releases/download/fastloess-v1.0.0+0/fastloess.v1.0.0.x86_64-apple-darwin.tar.gz"
[[fastloess]]
arch = "x86_64"
git-tree-sha1 = "0e14ebb8031eec3895ccf5ca666ebf4c663e3382"
libc = "glibc"
os = "linux"

    [[fastloess.download]]
    sha256 = "e89ba409c43d180296fb37510c4fd28e031ce49d503a533d50e239783ab0edff"
    url = "https://github.com/JuliaBinaryWrappers/fastloess_jll.jl/releases/download/fastloess-v1.0.0+0/fastloess.v1.0.0.x86_64-linux-gnu.tar.gz"
[[fastloess]]
arch = "x86_64"
git-tree-sha1 = "f6b890c3f2e7cc71ab515c6a0eab2344b24264d3"
os = "windows"

    [[fastloess.download]]
    sha256 = "8a382536aca5e7c9a6bfa73cc11eac7523a205742594df03e58aef8185bb4fb2"
    url = "https://github.com/JuliaBinaryWrappers/fastloess_jll.jl/releases/download/fastloess-v1.0.0+0/fastloess.v1.0.0.x86_64-w64-mingw32.tar.gz"
