# Autogenerated wrapper script for fastloess_jll for x86_64-apple-darwin
export libfastloess_jl

JLLWrappers.@generate_wrapper_header("fastloess")
JLLWrappers.@declare_library_product(libfastloess_jl, "@rpath/libfastloess_jl.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libfastloess_jl,
        "lib/libfastloess_jl.dylib",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
