# Autogenerated wrapper script for fastloess_jll for x86_64-linux-gnu
export libfastloess_jl

JLLWrappers.@generate_wrapper_header("fastloess")
JLLWrappers.@declare_library_product(libfastloess_jl, "libfastloess_jl.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libfastloess_jl,
        "lib/libfastloess_jl.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
