# Autogenerated wrapper script for fastloess_jll for x86_64-w64-mingw32
export libfastloess_jl

JLLWrappers.@generate_wrapper_header("fastloess")
JLLWrappers.@declare_library_product(libfastloess_jl, "fastloess_jl.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libfastloess_jl,
        "bin\\fastloess_jl.dll",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
